openapi: 3.0.0
info:
  title: Clinical
  version: 1.0.0
security:
  - bearerAuth: ["PROGRAMDATA-${programId}.WRITE", "CLINICALSERVICE.WRITE"]
paths:
  /submission/program/{programId}/registration:
    parameters:
      - name: programId
        description: the short name of the program
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get registration for a program
      description: returns the current in progress registration for a program if any
      responses:
        "200":
          description: "the current in progress registration or empty body if nothing found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Registration"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "403":
          $ref: "#/components/responses/ForbiddenError"
        "500":
          $ref: "#/components/responses/ServerError"
    post:
      summary: Upload a new registration file for a program
      description: This will validate and save the new registration file overwriting any existing registration
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                registrationFile:
                  type: string
                  format: binary
        description: the tsv registration file
        required: true
      responses:
        "400":
          description: "the file structure is invalid, couldn't be parsed correctly"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  code:
                    type: string
                    enum: ["TSV_PARSING_FAILED", "INVALID_FILE_NAME"]
              examples:
                TSVParseError:
                  value:
                    msg: "string"
                    code: "TSV_PARSING_FAILED"
                InvalidFileNameError:
                  value:
                    msg: "string"
                    code: "INVALID_FILE_NAME"

        "422":
          description: "invalid registration file"
          content:
            application/json:
              schema:
                type: object
                properties:
                  successful:
                    type: boolean
                    description: will be false in this case
                  errors:
                    type: array
                    items:
                      $ref: "#/components/schemas/RegistrationValidationError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "403":
          $ref: "#/components/responses/ForbiddenError"
        "500":
          $ref: "#/components/responses/ServerError"
        "201":
          description: "the file is valid and registration was created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateRegistration"
  /submission/program/{programId}/registration/{id}:
    delete:
      parameters:
        - name: id
          description: the id of the registration
          in: path
          required: true
          schema:
            type: string
        - name: programId
          description: the short name of the program
          in: path
          required: true
          schema:
            type: string
      responses:
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "403":
          $ref: "#/components/responses/ForbiddenError"
        "500":
          $ref: "#/components/responses/ServerError"
        "200":
          description: "the registration was deleted from db"
  /submission/program/{programId}/registration/{id}/commit:
    post:
      parameters:
        - name: id
          description: the id of the registration
          in: path
          required: true
          schema:
            type: string
        - name: programId
          description: the short name of the program
          in: path
          required: true
          schema:
            type: string
      responses:
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "403":
          $ref: "#/components/responses/ForbiddenError"
        "500":
          $ref: "#/components/responses/ServerError"
        "200":
          description: "the registration was committed and the donors / specimens / samples added to the clinical db"
          content:
            application/json:
              schema:
                type: object
                properties:
                  newSamples:
                    type: array
                    items:
                      type: string
  /clinical/donors:
    delete:
      parameters:
        - name: programId
          description: the short name of the program
          in: query
          required: true
          schema:
            type: string
      responses:
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "403":
          $ref: "#/components/responses/ForbiddenError"
        "500":
          $ref: "#/components/responses/ServerError"
        "200":
          description: "all donors deleted"
    get:
      parameters:
        - name: programId
          description: the short name of the program
          in: query
          required: true
          schema:
            type: string
      responses:
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "403":
          $ref: "#/components/responses/ForbiddenError"
        "500":
          $ref: "#/components/responses/ServerError"
        "200":
          description: "donors of program "
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object

  /health:
    get:
      responses:
        "500":
          description: "app is not fully healthy"
        "200":
          description: "all components reporting healthy status"
          content:
            application/json:
              schema:
                type: object

  /submission/schema:
    get:
      responses:
        "200":
          description: "the current loaded schema by the clinical submission"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /submission/schema/hack/refresh:
    post:
      description: force reload the schema from the schema service and override the cache
      responses:
        "200":
          description: "the current loaded schema by the clinical submission"
          content:
            application/json:
              schema:
                type: object
  /submission/schema/hack/replace:
    post:
      description: force replace the schema from the provided schema in body
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: "the current loaded schema by the clinical submission"
          content:
            application/json:
              schema:
                type: object
servers:
  - url: /
components:
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
    ServerError:
      description: Server error
    ForbiddenError:
      description: if the token has incorrect scopes
    NotFoundError:
      description: The requested resource was not found
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    RegistrationValidationError:
      type: object
      required:
        - fieldName
        - info
        - index
        - type
      properties:
        fieldName:
          type: string
          description: the field name that the error is related to
        info:
          type: object
          description: contains context information related to the error
          properties:
            value:
              type: string
              nullable: true
              description: the faulty value
            sampleSubmitterId:
              type: string
              nullable: true
              description: the sample Id in that row
            donorSubmitterId:
              type: string
              nullable: true
              description: the donor Id in that row
            specimenSubmitterId:
              type: string
              nullable: true
              description: the specimen Id in that row
          additionalProperties: true
        index:
          type: number
          format: integer
          description: the 0 based index of the row for this error
        type:
          type: string
          description: The name of the parameter
          enum:
            # data validation errors
            - SPECIMEN_BELONGS_TO_OTHER_DONOR
            - MUTATING_EXISTING_DATA
            - SAMPLE_BELONGS_TO_OTHER_SPECIMEN
            - NEW_SPECIMEN_CONFLICT
            - NEW_SAMPLE_CONFLICT
            - INVALID_PROGRAM_ID
            # dictionary schema errors
            - MISSING_REQUIRED_FIELD
            - INVALID_FIELD_VALUE_TYPE
            - INVALID_BY_REGEX
            - INVALID_BY_SCRIPT
            - INVALID_ENUM_VALUE

    Registration:
      type: object
      required:
        - _id
        - programId
        - creatorId
        - stats
        - records
      properties:
        _id:
          type: string
          description: the id of the registration
        programId:
          type: string
          description: the program short name this registration is for
        creator:
          type: string
          description: first name and last name of the user who created this registration
        batchName:
          type: string
          description: a file that must start with registration and have .tsv extension
        stats:
          type: object
          properties:
            newDonorIds:
              $ref: "#/components/schemas/RegistrationStat"
            newSpecimenIds:
              $ref: "#/components/schemas/RegistrationStat"
            newSampleIds:
              $ref: "#/components/schemas/RegistrationStat"
            alreadyRegistered:
              $ref: "#/components/schemas/RegistrationStat"
        records:
          type: array
          items:
            $ref: "#/components/schemas/Record"

    Record:
      required:
        - program_id
        - submitter_donor_id
        - gender
        - submitter_specimen_id
        - specimen_type
        - tumour_normal_designation
        - submitter_sample_id
        - sample_type
      properties:
        program_id:
          type: string
        submitter_donor_id:
          type: string
        gender:
          type: string
        submitter_specimen_id:
          type: string
        specimen_type:
          type: string
        tumour_normal_designation:
          type: string
        submitter_sample_id:
          type: string
        sample_type:
          type: string

    RegistrationStat:
      type: object

    CreateRegistration:
      required:
        - successful
      type: object
      properties:
        registration:
          $ref: "#/components/schemas/Registration"
        successful:
          type: boolean
          description: whether the file was valid or not
        errors:
          type: array
          description: list of all errors, should be empty on success
          items:
            $ref: "#/components/schemas/RegistrationValidationError"
