version: '2'

services:
  vault:
    image: vault
    volumes:
      - $PWD/logs/:/tmp/logs
      - ./vault:/scripts
    cap_add:
      - IPC_LOCK
    # mounted from the ./vault folder
    command: /scripts/vault.sh
    ports:
      - 8200:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: testing-token
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200

  clinicaldb:
    image: 'bitnami/mongodb:4.0'
    ports:
      - '27027:27017'
    volumes:
      - 'clinical_data:/bitnami'
    environment:
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: password
      MONGODB_DATABASE: clinical
      MONGODB_ROOT_PASSWORD: password123

  lectern:
    image: overture/lectern:edge
    depends_on:
      - lecterndb
    environment:
      PORT: 3000
      MONGO_URL: mongodb://admin:password@lecterndb:27017/lectern
      AUTH_ENABLED: 'false'
      VAULT_ENABLED: 'false'
    ports:
      - 3001:3000

  lecterndb:
    image: 'bitnami/mongodb:4.0'
    ports:
      - '27037:27017'
    volumes:
      - 'lectern_data:/bitnami'
    environment:
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: password
      MONGODB_DATABASE: lectern
      MONGODB_ROOT_PASSWORD: password123

volumes:
  clinical_data:
    driver: local
  lectern_data:
    driver: local
