version: '2'
services:
  clinical:
    image: 'icgcargo/clinical:edge'
    ports:
      - '3000:3000'
    environment:
      CLINICAL_DB_URL: 'mongodb://mongodb:27017/clinical'
      # has to be lower case
      LOG_LEVEL: debug
      INITIAL_SCHEMA_VERSION: '1.0'
      SCHEMA_NAME: 'ARGO Dictionary'
  mongodb:
    image: 'bitnami/mongodb:4.0'
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb_data:/bitnami'

volumes:
  mongodb_data:
    driver: local
